/**
 * @author Lars Brinker
 */
INSERT INTO
    `User` (
        `id`,
        `email`,
        `username`,
        `password`,
        `firstName`,
        `lastName`,
        `preposition`,
        `level`,
        `levelProgress`,
        `role`,
        `createdAt`,
        `updatedAt`
    )
VALUES
    (
        NULL,
        'admin@test.com',
        'admin',
        '$2b$06$m2Pa1b4zPQMhtxqbieZwx.H9cNd6Hcj1hBKg9AQ7Y7HiEmcBi0qPy',
        'admin',
        'admin',
        'van',
        99,
        999,
        'ADMIN',
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    ),
    (
        NULL,
        'olivia@hotmail.com',
        'Olivia-Green',
        '$2b$06$jfWexkwlC0q8dh6hPcSWCeUH8PESr5dQE.qPVQ3CHDEKepIIedFsG',
        'Olivia',
        'Green',
        '',
        1,
        100,
        'STUDENT',
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    ),
    (
        NULL,
        'max@hotmail.com',
        'MaxEco',
        '$2b$06$vnjOBW/JHPxfrRrkOyhkc.6rkG2IqFiXRZRcdwM2LJ.CjZTvkh3Be',
        'Max',
        'Eco',
        '',
        1,
        1,
        'MODERATOR',
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    );